### ISSUE TITLE
NotADirectoryError

### ISSUE THREAD

**Issue by AIisCool** [Shuweis/Rethinking-Alignment-in-Video-Super-Resolution-Transformers#5]
```
python inference_psrtrecurrent_reds.py
2022-12-19 03:27:01,603 INFO: Data: 100_psrtrecurrent_16f - C:/RethinkVSRAlignment-main/datasets/REDS4/sharp_bicubic/
2022-12-19 03:27:01,603 INFO: Model path: experiments/PSRT_Reccurrent/PSRT_REDS.pth
C:\Python310\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "C:\RethinkVSRAlignment-main\inference_psrtrecurrent_reds.py", line 122, in <module>
    main()
  File "C:\RethinkVSRAlignment-main\inference_psrtrecurrent_reds.py", line 67, in main
    imgs_lq, imgnames = read_img_seq(subfolder, return_imgname=True)
  File "C:\Python310\lib\site-packages\basicsr\data\data_util.py", line 28, in read_img_seq
    img_paths = sorted(list(scandir(path, full_path=True)))
  File "C:\Python310\lib\site-packages\basicsr\utils\misc.py", line 74, in _scandir
    for entry in os.scandir(dir_path):
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:/RethinkVSRAlignment-main/datasets/REDS4/sharp_bicubic\\000.png'
```

What am I doing wrong??

**Comment by Shuweis** [comment]
<img width="497" alt="image" src="https://user-images.githubusercontent.com/42030600/208389878-9b820f39-221b-4a91-8efd-838dba919312.png">
Maybe your file path has something wrong. You can check it.
